# Generated by Django 4.1 on 2023-02-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_jwt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
