# Generated by Django 4.1 on 2023-02-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericfileupload',
            name='test_name',
            field=models.CharField(default='aaaa', max_length=20),
        ),
    ]
