# Generated by Django 4.1 on 2023-02-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0002_genericfileupload_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericfileupload',
            name='test_name',
        ),
    ]
